-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public."group" RENAME COLUMN order TO seq;

ALTER TABLE IF EXISTS public."group_participants" RENAME COLUMN order TO seq;

ALTER TABLE IF EXISTS public."stage" RENAME COLUMN order TO seq;

ALTER TABLE IF EXISTS public."match"
    ADD COLUMN sequence jsonb NOT NULL DEFAULT '{}'::jsonb;

